### ISSUE TITLE
A new fork of Thali Onion Proxy

### ISSUE THREAD

**Issue by jehy** [tombailey/android-download-over-tor#1]
Hi! I wanted to implement the same thing and accidentally found your project. It didn't help me much but I made my own fork of Thali Onion Proxy and I think that it can be useful for you. Also I have some good code samples on how to use Thali Onion Proxy with apache's httpClient.  If you are interested, you can see it here: https://github.com/jehy/Tor_Onion_Proxy_Library
It also contains latest Tor binaries and JtorCtl library.

**Comment by tombailey** [comment]
Looks good, I will take a look at this 😄
